### ISSUE TITLE
TypeError: require.cache.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by wzup** [krakenjs/adaro#109]
This line in my code throws:

```
app.engine('dust', adaro.dust({}));
```

Error:
```
  ● Test suite failed to run

    TypeError: require.cache.hasOwnProperty is not a function

      at unload (node_modules\freshy\index.js:54:23)
      at getFresh (node_modules\freshy\index.js:20:5)
      at node_modules\freshy\index.js:94:19
      at exports.create (node_modules\adaro\lib\engine.js:43:16)
      at Object.<anonymous> (app.js:53:26)
      at Object.<anonymous> (__tests__\one.test.js:8:11)
```

Why does it happen? How to solve?

**Comment by baldercm** [comment]
Same error here after upgrading from nodejs v7 to v8.

Seems like current freshy version does not work in node v8. See https://github.com/totherik/freshy/issues/10#issuecomment-305771527

**Comment by grawk** [comment]
@wzup which version of node were/are you using? @baldercm thanks for identifying that. we've seen freshy as a source of this same error in other contexts during our node7/node8 acceptance testing. will link any related issues to this one.

**Comment by erchaves** [comment]
This is now fixed in the freshy package https://github.com/totherik/freshy/issues/10#issuecomment-308461601

The Adaro project might consider pinning their package.js version of freshy to 1.0.3 or higher. But a user of Adaro can also fix this problem by re-installing adaro which will pull the latest (fixed) version of freshy.

**Comment by grawk** [comment]
Since no changes are required here, I'll close this issue. Thank you for the bug report!
